---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: faces
spec:
  interval: 10m
  url: https://github.com/BuoyantIO/faces-demo
  ref:
    branch: main
  ignore: |
    /*
    !/k8s/01-base/*-profile.yaml
    !/k8s/01-base/faces.yaml
    !/k8s/01-base/faces-gui.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: faces
spec:
  targetNamespace: faces
  interval: 10m
  path: "./k8s/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: faces
  patches:
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/env
          value:
            - name: FACES_SERVICE
              value: "smiley"
            - name: ERROR_FRACTION
              value: "0"
            - name: DELAY_BUCKETS
              value: "0,5,10,15,20,50,200,500,1500"
            - name: SMILEY
              value: "HeartEyes"
      target:
        kind: Deployment
        name: smiley
    - patch: |
        - op: replace
          path: /spec/template/spec/containers/0/env/1
          value:
            name: ERROR_FRACTION
            value: "0"
      target:
        kind: Deployment
        name: (face|color)
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/env
          value:
            - name: ERROR_FRACTION
              value: "0"
            - name: COLOR_foo
              value: lightgray
      target:
        kind: Deployment
        name: faces-gui
